apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-nginx
spec:
  strategy:
    rollingUpdate:
    #maxSurge=0 maxUnavailable>0, first offline then online
    #maxSurge>0 maxUnavailable=0, first online then offline
    #max number exceed replicas, means the max online replicas are maxSurge+replicas, or can use 20%
      maxSurge: 1
    #max number of unavailable pod
      maxUnavailable: 5
  selector:
    matchLabels:
      run: my-nginx
  replicas: 10
  # 
  minReadySeconds: 60
  template:
    metadata:
      labels:
        run: my-nginx
    spec:
      containers:
      - name: my-nginx
        image: nginx
        ports:
        - containerPort: 80
